//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsMsMqClient.AcademicService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcademicService.IAcademicService")]
    public interface IAcademicService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/CreateCar")]
        void CreateCar(string Car);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/CreateCar")]
        System.Threading.Tasks.Task CreateCarAsync(string Car);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/UpdateCar")]
        void UpdateCar(string updatedCar);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/UpdateCar")]
        System.Threading.Tasks.Task UpdateCarAsync(string updatedCar);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/RemoveCar")]
        void RemoveCar(string CarId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/RemoveCar")]
        System.Threading.Tasks.Task RemoveCarAsync(string CarId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/CreateOrder")]
        void CreateOrder(string Order);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/CreateOrder")]
        System.Threading.Tasks.Task CreateOrderAsync(string Order);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/UpdateOrder")]
        void UpdateOrder(string updatedOrder);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/UpdateOrder")]
        System.Threading.Tasks.Task UpdateOrderAsync(string updatedOrder);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/RemoveOrder")]
        void RemoveOrder(string OrderId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/RemoveOrder")]
        System.Threading.Tasks.Task RemoveOrderAsync(string OrderId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAcademicService/CreateCiO")]
        void CreateCiO(string CiO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/CreateCiO")]
        System.Threading.Tasks.Task CreateCiOAsync(string CiO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/UpdateCiO")]
        void UpdateCiO(string updatedCiO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/UpdateCiO")]
        System.Threading.Tasks.Task UpdateCiOAsync(string updatedCiO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/RemoveCiO")]
        void RemoveCiO(string CiOId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action= "http://tempuri.org/IAcademicService/RemoveCiO")]
        System.Threading.Tasks.Task RemoveCiOAsync(string CiOId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcademicServiceChannel : WebFormsMsMqClient.AcademicService.IAcademicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcademicServiceClient : System.ServiceModel.ClientBase<WebFormsMsMqClient.AcademicService.IAcademicService>, WebFormsMsMqClient.AcademicService.IAcademicService {
        
        public AcademicServiceClient() {
        }
        
        public AcademicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcademicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcademicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateCar(string Car) {
            base.Channel.CreateCar(Car);
        }
        
        public System.Threading.Tasks.Task CreateCarAsync(string Car) {
            return base.Channel.CreateCarAsync(Car);
        }
        
        public void UpdateCar(string updatedCar) {
            base.Channel.UpdateCar(updatedCar);
        }
        
        public System.Threading.Tasks.Task UpdateCarAsync(string updatedCar) {
            return base.Channel.UpdateCarAsync(updatedCar);
        }
        
        public void RemoveCar(string CarId) {
            base.Channel.RemoveCar(CarId);
        }
        
        public System.Threading.Tasks.Task RemoveCarAsync(string CarId) {
            return base.Channel.RemoveCarAsync(CarId);
        }
        
        public void CreateOrder(string Order) {
            base.Channel.CreateOrder(Order);
        }
        
        public System.Threading.Tasks.Task CreateOrderAsync(string Order) {
            return base.Channel.CreateOrderAsync(Order);
        }
        
        public void UpdateOrder(string updatedOrder) {
            base.Channel.UpdateOrder(updatedOrder);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(string updatedOrder) {
            return base.Channel.UpdateOrderAsync(updatedOrder);
        }
        
        public void RemoveOrder(string OrderId) {
            base.Channel.RemoveOrder(OrderId);
        }
        
        public System.Threading.Tasks.Task RemoveOrderAsync(string OrderId) {
            return base.Channel.RemoveOrderAsync(OrderId);
        }
        
        public void CreateCiO(string CiO) {
            base.Channel.CreateCiO(CiO);
        }
        
        public System.Threading.Tasks.Task CreateCiOAsync(string CiO) {
            return base.Channel.CreateCiOAsync(CiO);
        }
        
        public void UpdateCiO(string updatedCiO) {
            base.Channel.UpdateCiO(updatedCiO);
        }
        
        public System.Threading.Tasks.Task UpdateCiOAsync(string updatedCiO) {
            return base.Channel.UpdateCiOAsync(updatedCiO);
        }
        
        public void RemoveCiO(string CiOId) {
            base.Channel.RemoveCiO(CiOId);
        }
        
        public System.Threading.Tasks.Task RemoveCiOAsync(string CiOId) {
            return base.Channel.RemoveCiOAsync(CiOId);
        }
    }
}
